server:
  port: 9192

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_dev_schema
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
      